version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://server1-db-1:5432/db_inmueble
      SPRING_DATASOURCE_USERNAME: postgres 
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./target:/app/target
    networks:
      - microservice
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: db_inmueble
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    ports:
      - "5432:5432"
    networks:
      - microservice
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_inmueble"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  microservice:
    external: true
